# Generated by Django 6.0 on 2026-01-27 04:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('titulacion', models.CharField(max_length=100)),
                ('imginstructor', models.ImageField(blank=True, null=True, upload_to='imginstructor/')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('TEC', 'Tecnología'), ('ADM', 'Administración'), ('IDI', 'Idiomas')], max_length=3)),
                ('duracion_horas', models.PositiveIntegerField()),
                ('cupo_maximo', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='Cursos.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=20)),
                ('fecha_matricula', models.DateField(default=django.utils.timezone.now)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='Cursos.curso')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='Cursos.instructor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('documento_identidad', 'curso'), name='unique_estudiante_curso')],
            },
        ),
    ]
